use_frameworks!

platform :ios, '9.0'

target 'XLAccountManager_Example' do
  pod 'XLAccountManager', :path => '../'

  target 'XLAccountManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
